name: Weekly Team Sync
on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  create_issue:
    name: Create monthly POAM issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create monthly POAM issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: POAM - [MONTH] '24
          ASSIGNEES: mahoneycm
          LABELS: "Type: Task"
          BODY: |
            # Summary

            POAM for [MONTH] 2024

            - [ ] USWDS
            - [ ] USWDS-Site
            - [ ] USWDS-Sandbox
            - [ ] USWDS-Next
            - [ ] USWDS-Compile
            - [ ] USWDS-Tutorial
            - [ ] Public Sans
          PINNED: false
          CLOSE_PREVIOUS: false
